queue:
  name: Hosted VS2017

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'

- script: yarn
  displayName: Install dependencies

- script: yarn test
  displayName: Run unit tests

- script: yarn add --global npx wait-on
  displayName: Install npx and wait-on

- script: yarn start & wait-on http://localhost:3000
  displayName: Run server for Cypress

- script: npx cypress run
  displayName: Run Cypress tests

- task: RichCodeNavIndexer@0
  inputs:
    serviceConnection: 'rich-code-nav'
    githubServiceConnection: 'vsls-contrib'
    languages: typescript
