queue:
  name: Hosted VS2017

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'

- script: yarn
  displayName: Install dependencies

- script: yarn test
  displayName: Run unit tests

- script: yarn global add npx
  displayName: Install npx

- script: start /B yarn start --silent
  displayName: Run server for Cypress

- script: npx cypress run
  displayName: Run Cypress tests

- task: RichCodeNavIndexer@0
  inputs:
    serviceConnection: 'rich-code-nav'
    githubServiceConnection: 'vsls-contrib'
    languages: typescript
