queue:
  name: Hosted VS2017

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'

- script: yarn
  displayName: Install dependencies

- script: yarn test
  displayName: Run tests

- task: RichCodeNavIndexer@0
  inputs:
    serviceConnection: 'rich-code-nav'
    nugetServiceConnection: 'rich-code-nav-nuget'
    githubServiceConnection: 'vsls-contrib'
    languages: javascript
    serviceEndpoint: 'https://prod.richnav.vsengsaas.visualstudio.com'
